#!/usr/bin/env bash

# Analise com PHPSTAN
./vendor/bin/phpstan analyse
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com o PHPSTAN. Corrija antes de continuar...";
    exit 1;
fi;

# Rodar os testes
php artisan test --parallel
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui algum teste. Corrija antes de continuar...";
    exit 1;
fi;

# FORMATAR com o Laravel Pint
STAGGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true
for FILE in $STAGGED_FILES
do
./vendor/bin/pint "${FILE}";
git add "${FILE}";
done;

exit 0;
